name: Manually Deploy to Heroku

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: "3355817d-e6f4-4dd2-ad19-ce56299ab439"
          heroku_app_name: "theavikaub2"
          heroku_email: "theavi.02@proton.me"
          usedocker: true
          docker_heroku_process_type: web
          stack: "heroku-20"
          region: "eu"
          
